"""initial schema

Revision ID: fa5ca2588506
Revises: 
Create Date: 2026-08-08 17:20:41.450469
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fa5ca2588506'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explanations',
    sa.Column('rule_id', sa.String(length=128), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('simple_text', sa.Text(), nullable=False),
    sa.Column('technical_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'context_hash', name='uq_explanations_rule_context')
    )
    op.create_index(op.f('ix_explanations_context_hash'), 'explanations', ['context_hash'], unique=False)
    op.create_index(op.f('ix_explanations_rule_id'), 'explanations', ['rule_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('domains',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', name='verification_status', native_enum=False), nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'hostname', name='uq_domains_user_hostname')
    )
    op.create_index(op.f('ix_domains_hostname'), 'domains', ['hostname'], unique=False)
    op.create_index(op.f('ix_domains_user_id'), 'domains', ['user_id'], unique=False)
    op.create_table('scans',
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'COLLECTING', 'JUDGING', 'EXPLAINING', 'COMPLETE', 'FAILED', name='scan_status', native_enum=False), nullable=False),
    sa.Column('tier', sa.Enum('PUBLIC', 'VERIFIED', name='scan_tier', native_enum=False), nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', 'D', 'F', name='scan_grade', native_enum=False), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('current_stage', sa.String(length=16), nullable=True),
    sa.Column('stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_domain_id'), 'scans', ['domain_id'], unique=False)
    op.create_table('findings',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='finding_severity', native_enum=False), nullable=False),
    sa.Column('cvss_vector', sa.String(length=64), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('owasp_category', sa.String(length=128), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('simple_explanation', sa.Text(), nullable=False),
    sa.Column('technical_explanation', sa.Text(), nullable=False),
    sa.Column('remediation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_rule_id'), 'findings', ['rule_id'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_table('scan_raw',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('collector', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_raw_scan_id'), 'scan_raw', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_raw_scan_id'), table_name='scan_raw')
    op.drop_table('scan_raw')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_rule_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_scans_domain_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_domains_user_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_hostname'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_explanations_rule_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_context_hash'), table_name='explanations')
    op.drop_table('explanations')
    # ### end Alembic commands ###
